# Generated by Django 3.2.13 on 2022-05-18 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_particularthread_project_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbidders',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
