# Generated by Django 3.2.13 on 2022-05-21 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectbidders_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='OrderProjected',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deliver', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField()),
                ('project_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_projected',
            },
        ),
    ]
