# Generated by Django 3.2.13 on 2022-05-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220522_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprojected',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
