# Generated by Django 3.2.13 on 2022-05-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_orderprojected_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprojected',
            name='is_revision',
            field=models.BooleanField(default=False),
        ),
    ]
